artifact_location: file:///C:/Users/JanTilles/Documents/Turku AMK/Python Training/Object
  Detection/runs/mlflow/0
creation_time: 1740586224028
experiment_id: '0'
last_update_time: 1740586224028
lifecycle_stage: active
name: Default
