artifact_location: file:///C:/Users/JanTilles/Documents/Turku AMK/Python Training/Object
  Detection/runs/mlflow/179996807598300406
creation_time: 1740586224063
experiment_id: '179996807598300406'
last_update_time: 1740586224063
lifecycle_stage: active
name: /Shared/Ultralytics
